### ISSUE TITLE
pkg throws errors on executing post-install scripts

### ISSUE THREAD

**Issue by Culsu** [TLINDEN/jaildk#6]
Hi there,
i don't know why yet, but pkg 1.15.10 is throwing errors when installing it with pkg-static inside a jail. this can also be reproduced by install pcre (dependency of nginx). This only happens inside a jail (e.g. jaildk blogin myjail -> pkg install nginx)

e.g.
```
pkg install pkg
[...]
[1/1] Installing pkg-1.15.10...
[1/1] Extracting pkg-1.15.10: 100%
jexec: jail "myjail" is dying
pkg: POST-INSTALL script failed
 ------
pkg install nginx
[...]
[1/2] Fetching nginx-1.18.0_25,2.txz: 100%  446 KiB 456.4kB/s    00:01
[2/2] Fetching pcre-8.44.txz: 100%    1 MiB   1.3MB/s    00:01
Checking integrity... done (0 conflicting)
[1/2] Installing pcre-8.44...
[1/2] Extracting pcre-8.44: 100%
jexec: jail "myjail" is dying
pkg: POST-INSTALL script failed

```
I already tried using a completely unmodified build base (commented out symlinks, and removes in jaildk_base), and mounted everything rw. I still get the same error.
Any guesses?

Cheers
FS

**Comment by TLINDEN** [comment]
Fixed with 763b57a, thanks!

**Comment by TLINDEN** [comment]
PS: I changed `mtree -u` to `mtree -Ue` in 7b827c6, which is a little bit more relaxed.

**Comment by TLINDEN** [comment]
More issues with mtree: no default mtree.conf exists, which must exist for every jail in case it uses a build base, because there are 3 symlinks being created. So, I'd rather change this to 1 symlink just pointing to /tmp which always exists. Also the `ln -s`  doesn't work because the directories already exist in a newly built base.

Take a look... 37efdcb2

**Comment by Culsu** [comment]
The mtree.conf template is being created on a fresh setup.
Probably we should add a routine to create a default (cp .template -> $jail) mtree.conf if it's missing?
I added the /var/(run|cache|tmp) to the removelist in [763b57a](https://github.com/TLINDEN/jaildk/commit/763b57a3e671381e012a791466ae151504de2a18).
Thus they still exist on a newly created build-base, but not in a trimmed down (non-build) base.
Non existence leads to problems with pkg (e.g. when installing nginx) when using the non-build base.

**Comment by Culsu** [comment]
Dug a little deeper, found something:
```
DBG(3)[14910]> Scripts: executing
--- BEGIN ---
set -- pkg-1.15.10
if ! /usr/sbin/service ldconfig restart >/dev/null; then
                if [ -z "${INSTALL_AS_USER}" ]; then
                        exit 1
                fi
        fi
Scripts: --- END ---
jexec: jail "myjail" is dying
pkg: POST-DEINSTALL script failed
```

Executing `/usr/sbin/service ldconfig restart` inside the jail throws the beforehand observed `jexec: jail "myjail" is dying` - and most likely the `exit 1` to the failure of the pkg POST-(de)install script.

**Comment by TLINDEN** [comment]
It's a shell config | environment problem. Doesn't happen this way:
```
blogin myjail
env - csh
service ldconfig restart
```
However, it's unclear which part of %ENV causes this :(

**Comment by TLINDEN** [comment]
there:
```
(jail) root@e3:~ # setenv | grep -i jail
JAIL=test
```
No idea what set's this, but this is the root cause.
